steps:
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    id: Build Dataflow Flex Template
    args: ['dataflow', 'flex-template', 'build',
           'gs://$_DATAFLOW_BASE_BUCKET/$_DATAFLOW_TEMPLATE_NAME.json',
           '--image-gcr-path=$_REGION_ID-docker.pkg.dev/$PROJECT_ID/$_ARTIFACT_REGISTRY_REPOSITORY/$_ARTIFACT_REGISTRY_IMAGE_NAME:$COMMIT_SHA',
           '--flex-template-base-image=PYTHON3',
           '--sdk-language=PYTHON',
           '--py-path=.',
           '--env=FLEX_TEMPLATE_PYTHON_PY_FILE=$_DATAFLOW_PYTHON_FILE_PATH',
           '--env=FLEX_TEMPLATE_PYTHON_REQUIREMENTS_FILE=$_DATAFLOW_REQUIREMENTS_FILE_PATH'
    ]
    waitFor: ['-']
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    id: Run Dataflow Flex Template
    args: ['dataflow', 'flex-template', 'run', '$_DATAFLOW_JOB_NAME',
           '--template-file-gcs-location=gs://$_DATAFLOW_BASE_BUCKET/$_DATAFLOW_TEMPLATE_NAME.json',
           '--parameters=project_id=$PROJECT_ID,playback_pubsub_subscription_name=$_PLAYBACK_PUBSUB_SUBSCRIPTION_NAME,engagement_pubsub_subscription_name=$_ENGAGEMENT_PUBSUB_SUBSCRIPTION_NAME,quality_pubsub_subscription_name=$_QUALITY_PUBSUB_SUBSCRIPTION_NAME,notifications_pubsub_topic=$_NOTIFICATIONS_PUBSUB_TOPIC_NAME,firestore_collection=$_FIRESTORE_COLLECTION_NAME,bigquery_dataset=$_BIGQUERY_DATASET,user_bigquery_table=$_USER_BIGQUERY_TABLE,episode_bigquery_table=$_EPISODE_BIGQUERY_TABLE',
           '--region=$_REGION_ID',
           '--max-workers=1',
          #  '--update'
    ]
    waitFor: ['Build Dataflow Flex Template']
options:
  logging: STACKDRIVER_ONLY
substitutions:
  _DATAFLOW_BASE_BUCKET: edem-serverless-saul
  _DATAFLOW_JOB_NAME: CICD-streaming-job
  _DATAFLOW_TEMPLATE_NAME: streaming_template
  _REGION_ID: europe-west1
  _ARTIFACT_REGISTRY_REPOSITORY: CI-CD-Dataflow
  _ARTIFACT_REGISTRY_IMAGE_NAME: streaming-dataflow-image
  _DATAFLOW_PYTHON_FILE_PATH: edem_realtime_recommendation_engine.py
  _DATAFLOW_REQUIREMENTS_FILE_PATH: requirements.txt
  _PLAYBACK_PUBSUB_SUBSCRIPTION_NAME: playback-subscription
  _ENGAGEMENT_PUBSUB_SUBSCRIPTION_NAME: engagement-subscription
  _QUALITY_PUBSUB_SUBSCRIPTION_NAME: quality-subscription
  _NOTIFICATIONS_PUBSUB_TOPIC_NAME: notifications-topic
  _FIRESTORE_COLLECTION_NAME: firestore-collection
  _BIGQUERY_DATASET: edem_dataset
  _USER_BIGQUERY_TABLE: tabla_edem_dataset1
  _EPISODE_BIGQUERY_TABLE: tabla_edem_dataset2